/*
 * Copyright (c) 2022-2024.
 * Author Peter Placzek (tada5hi)
 * For the full copyright and license information,
 * view the LICENSE file that was distributed with this source code.
 */

import { BadRequestError } from '@privateaim/errors';
import { isNameValid } from '@authup/core-kit';
import { createValidator } from '@validup/zod';
import { z } from 'zod';
import type { Analysis } from './entity.ts';
import { TypedContainer, ValidatorGroup } from '@privateaim/kit';
import { ImageAttributeCommandArgumentsValidator } from './validator-image-command-argument.ts';

export class AnalysisValidator extends TypedContainer<Analysis> {
    protected override initialize() {
        super.initialize();

        this.mount(
            'projectId',
            { group: ValidatorGroup.CREATE },
            createValidator(z.uuid()),
        );

        // URL-friendly identifier (slug). Optional on input — auto-generated by the
        // service when omitted. When provided, it must satisfy authup's name rules
        // (no whitespace, only [a-z0-9-_.]) so it stays consistent with other entities.
        this.mount(
            'name',
            { optional: true },
            createValidator(z.string().trim().toLowerCase().min(3)
                .max(128)
                .check((ctx) => {
                    try {
                        isNameValid(ctx.value, { throwOnFailure: true });
                    } catch (e) {
                        ctx.issues.push({
                            input: ctx.value,
                            code: 'custom',
                            message: e instanceof Error ? e.message : 'The analysis name is not valid.',
                        });
                    }
                })),
        );

        // Human-readable label shown in the UI. Free-form, optional.
        this.mount(
            'displayName',
            { optional: true },
            createValidator(z.string().min(3).max(256).nullable()),
        );

        this.mount(
            'description',
            { optional: true },
            createValidator(z.string().min(5).max(4096).nullable()),
        );

        this.mount(
            'masterImageId',
            { optional: true },
            createValidator(z.uuid().nullable()),
        );

        this.mount(
            'registryId',
            { optional: true },
            createValidator(z.uuid().nullable()),
        );

        const commandArgumentValidator = new ImageAttributeCommandArgumentsValidator();
        // image_command_executable
        this.mount('imageCommandArguments', { optional: true }, (ctx) => {
            if (ctx.value == null) {
                return ctx.value;
            }

            if (!Array.isArray(ctx.value)) {
                throw new BadRequestError('imageCommandArguments must be an array.');
            }

            const promises = ctx.value.map((child) => commandArgumentValidator.run(child, {
                group: ctx.group,
                flat: false,
                path: ctx.path,
            }));

            return Promise.all(promises);
        });
    }
}
