/*
 * Copyright (c) 2022-2024.
 * Author Peter Placzek (tada5hi)
 * For the full copyright and license information,
 * view the LICENSE file that was distributed with this source code.
 */

import { isNameValid } from '@authup/core-kit';
import { Container } from 'validup';
import { createValidator } from '@validup/adapter-zod';
import { z } from 'zod';
import type { Project } from './entity.ts';

export class ProjectValidator extends Container<Project> {
    protected initialize() {
        super.initialize();

        // URL-friendly identifier (slug). Optional on input — auto-generated by
        // the service when omitted. When provided, it must satisfy authup's name
        // rules (no whitespace, only [a-z0-9-_.]) so it stays consistent with
        // other entities.
        const nameValidator = createValidator(z.string().trim().toLowerCase().min(3)
            .max(128)
            .check((ctx) => {
                try {
                    isNameValid(ctx.value, { throwOnFailure: true });
                } catch (e) {
                    ctx.issues.push({
                        input: ctx.value,
                        code: 'custom',
                        message: e instanceof Error ? e.message : 'The project name is not valid.',
                    });
                }
            }));
        this.mount(
            'name',
            { optional: true },
            nameValidator,
        );

        // Human-readable label shown in the UI. Free-form, optional.
        this.mount(
            'display_name',
            { optional: true },
            createValidator(z.string().min(3).max(256).nullable()),
        );

        this.mount(
            'description',
            { optional: true },
            createValidator(z.string().min(5).max(4096).nullable()),
        );

        this.mount(
            'master_image_id',
            { optional: true },
            createValidator(z.uuid().nullable()),
        );
    }
}
